version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"  # Changez 5000 -> 5001
    volumes:
      - ./backend:/app
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network:
    driver: bridge
