version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  web:
    build: .
    container_name: web_app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/"
    command: ["sh", "-c", "sleep 5 && python app/init_db.py"]

volumes:
  mongo_data:
