# Generated by Django 3.2.25 on 2025-04-09 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_academic_level', models.CharField(choices=[('bac', 'Baccalauréat'), ('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], max_length=10, verbose_name='Niveau académique atteint')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre'), ('P', 'Préfère ne pas préciser')], max_length=1, verbose_name='Sexe')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='Photo de profil')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShortTermGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Objectif à court terme')),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_term_goals', to='users.goals')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_experience_years', models.PositiveIntegerField(verbose_name="Nombre d'années d'expérience professionnelle")),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_background', to='users.person')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('es', 'Espagnol'), ('de', 'Allemand'), ('zh', 'Chinois'), ('ar', 'Arabe')], max_length=2, verbose_name='Langue préférée')),
                ('learning_mode', models.CharField(choices=[('video', 'Vidéo'), ('text', 'Support de cours écrit'), ('practice', 'Learning by doing')], max_length=10, verbose_name="Mode d'apprentissage préféré")),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='users.person')),
            ],
        ),
        migrations.CreateModel(
            name='LongTermGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Objectif à long terme')),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_term_goals', to='users.goals')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Poste occupé')),
                ('company', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='Poste actuel')),
                ('description', models.TextField(blank=True, verbose_name='Description des responsabilités')),
                ('professional_background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.professionalbackground')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Centre d'intérêt")),
                ('preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='users.preferences')),
            ],
        ),
        migrations.AddField(
            model_name='goals',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='users.person'),
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name="Domaine d'étude")),
                ('institution', models.CharField(max_length=255, verbose_name="Nom de l'institution")),
                ('year_of_completion', models.PositiveIntegerField(verbose_name="Année d'obtention")),
                ('academic_background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_of_study', to='users.academicbackground')),
            ],
        ),
        migrations.AddField(
            model_name='academicbackground',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_background', to='users.person'),
        ),
    ]
