# Generated by Django 3.2.25 on 2025-05-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='predicted_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Niveau prédit'),
        ),
    ]
