# Generated by Django 4.2.24 on 2025-09-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20250521_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('file_path', models.TextField(verbose_name='Chemin du fichier')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('error', 'Erreur')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(verbose_name='Démarré à')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé à')),
                ('imported_count', models.IntegerField(default=0, verbose_name='Nombre importés')),
                ('updated_count', models.IntegerField(default=0, verbose_name='Nombre mis à jour')),
                ('error_count', models.IntegerField(default=0, verbose_name="Nombre d'erreurs")),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='Données de résultat')),
            ],
            options={
                'verbose_name': "Log d'importation",
                'verbose_name_plural': "Logs d'importation",
                'ordering': ['-started_at'],
            },
        ),
    ]
